# Generated by Django 5.2.5 on 2025-11-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Color, Talla, Marca', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('color', 'Color'), ('talla', 'Talla/Tamaño'), ('texto', 'Texto'), ('numero', 'Número')], default='texto', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('posicion', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text='Ej: Rojo, S, Nike', max_length=100)),
                ('codigo_color', models.CharField(blank=True, help_text='Para colores: código HEX (#FF0000)', max_length=7, null=True)),
                ('posicion', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.atributo')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributos',
                'ordering': ['atributo', 'posicion', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='VarianteAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.valoratributo')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.variante')),
            ],
            options={
                'verbose_name': 'Atributo de Variante',
                'verbose_name_plural': 'Atributos de Variantes',
                'unique_together': {('variante', 'valor_atributo')},
            },
        ),
    ]
