# Generated by Django 5.2.5 on 2025-10-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'ordering': ['talla'], 'verbose_name': 'Variante de producto', 'verbose_name_plural': 'Variantes de productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='gestionar_inventario',
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together={('producto', 'talla')},
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Categoría principal (Ej: Ropa, Accesorios)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria', verbose_name='Categoría/Estilo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Solo para accesorios de marca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock total'),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío para usar el precio del producto', max_digits=10, null=True, verbose_name='Precio específico'),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock de esta talla'),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='talla',
            field=models.CharField(help_text='Ej: S, M, L, XL o 36, 38, 40', max_length=20, verbose_name='Talla'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='productos_p_estado_ec69d1_idx'),
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='nombre',
        ),
    ]
