# Generated by Django 5.2.5 on 2025-11-06 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_atributo_valoratributo_varianteatributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='colecciones/')),
                ('posicion', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar en página principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='coleccion',
            field=models.ForeignKey(blank=True, help_text='Colección a la que pertenece esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='productos.coleccion'),
        ),
    ]
