# Generated by Django 5.2.5 on 2025-11-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_coleccion_categoria_coleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
