# Generated by Django 5.2.5 on 2025-11-06 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='material',
        ),
        migrations.AddField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(blank=True, help_text='Colección a la que pertenece este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.coleccion'),
        ),
    ]
