# Generated by Django 5.2.5 on 2025-11-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_estilo_remove_producto_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['posicion', 'created_at'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AddField(
            model_name='imagen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='posicion',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.TextField(blank=True, default='', help_text='URL alternativa si no se usa archivo'),
        ),
    ]
