# Generated by Django 5.2.5 on 2025-11-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_imagen_options_imagen_created_at_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='imagen',
        ),
    ]
