# Generated by Django 5.2.5 on 2025-11-07 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_imagen_from_coleccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'ordering': ['nombre'], 'verbose_name': 'Colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='posicion',
        ),
    ]
