# Generated by Django 5.2.5 on 2025-11-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_posicion_from_coleccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='posicion',
        ),
    ]
