# Generated by Django 5.2.5 on 2025-11-07 16:48

from django.db import migrations


def crear_coleccion_basica(apps, schema_editor):
    """
    Crea la colección 'Básica' si no existe y asigna todos los productos 
    que no tienen colección a esta colección por defecto.
    """
    Coleccion = apps.get_model('productos', 'Coleccion')
    Producto = apps.get_model('productos', 'Producto')
    
    # Crear o obtener la colección Básica
    coleccion_basica, created = Coleccion.objects.get_or_create(
        slug='basica',
        defaults={
            'nombre': 'Básica',
            'descripcion': 'Colección por defecto para productos sin colección específica',
            'activo': True,
            'destacada': False
        }
    )
    
    # Asignar todos los productos sin colección a la colección Básica
    productos_sin_coleccion = Producto.objects.filter(coleccion__isnull=True)
    count = productos_sin_coleccion.update(coleccion=coleccion_basica)
    
    if created:
        print(f"✓ Colección 'Básica' creada exitosamente")
    else:
        print(f"✓ Colección 'Básica' ya existía")
    
    if count > 0:
        print(f"✓ {count} producto(s) asignado(s) a la colección 'Básica'")


def revertir_coleccion_basica(apps, schema_editor):
    """
    Revierte la migración eliminando la asignación a la colección Básica
    (opcional: puedes dejar los productos asignados o eliminar la colección)
    """
    Coleccion = apps.get_model('productos', 'Coleccion')
    
    # Opción 1: Solo eliminar la colección Básica (los productos quedarán sin colección)
    Coleccion.objects.filter(slug='basica').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_posicion_from_categoria'),
    ]

    operations = [
        migrations.RunPython(crear_coleccion_basica, revertir_coleccion_basica),
    ]
