# Generated by Django 5.2.5 on 2025-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_crear_coleccion_basica'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la colección', null=True, upload_to='colecciones/'),
        ),
    ]
