# Generated by Django 5.2.5 on 2025-11-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_categoria_imagen_coleccion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono (opcional)', max_length=50)),
                ('dias_devolucion', models.PositiveIntegerField(default=30, help_text='Días permitidos para devolución')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de Devolución',
                'verbose_name_plural': 'Políticas de Devolución',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Shipping & Delivery', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción general de la política de envío')),
                ('tiempo_nacional', models.CharField(blank=True, help_text='Ej: 3-6 días', max_length=100)),
                ('tiempo_internacional', models.CharField(blank=True, help_text='Ej: 12-26 días', max_length=100)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío estándar', max_digits=10)),
                ('envio_gratis_desde', models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo para envío gratis', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Información de Envío',
                'verbose_name_plural': 'Información de Envío',
            },
        ),
        migrations.CreateModel(
            name='ProductCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(choices=[('icon-machine', 'Machine Wash'), ('icon-iron', 'Iron'), ('icon-bleach', 'Bleach'), ('icon-dry-clean', 'Dry Clean'), ('icon-tumble-dry', 'Tumble Dry')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_instructions', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Instrucción de Cuidado',
                'verbose_name_plural': 'Instrucciones de Cuidado',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Característica del Producto',
                'verbose_name_plural': 'Características del Producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Material del Producto',
                'verbose_name_plural': 'Materiales del Producto',
                'ordering': ['orden'],
            },
        ),
    ]
