# Generated by Django 5.2.5 on 2025-11-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_returnpolicy_shippinginfo_productcare_productfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_content', models.TextField(blank=True, help_text='HTML para la sección Features. Ej: <li>Front button placket</li>')),
                ('materials_content', models.TextField(blank=True, help_text='HTML para Materials Care. Ej: <li>Content: 100% Cotton</li>')),
                ('care_icon_1', models.CharField(default='icon-machine', help_text='Clase CSS del ícono 1', max_length=50)),
                ('care_text_1', models.CharField(default='Machine wash max. 30ºC. Short spin.', max_length=200)),
                ('care_icon_2', models.CharField(default='icon-iron', help_text='Clase CSS del ícono 2', max_length=50)),
                ('care_text_2', models.CharField(default='Iron maximum 110ºC.', max_length=200)),
                ('care_icon_3', models.CharField(default='icon-bleach', help_text='Clase CSS del ícono 3', max_length=50)),
                ('care_text_3', models.CharField(default='Do not bleach/bleach.', max_length=200)),
                ('care_icon_4', models.CharField(default='icon-dry-clean', help_text='Clase CSS del ícono 4', max_length=50)),
                ('care_text_4', models.CharField(default='Do not dry clean.', max_length=200)),
                ('care_icon_5', models.CharField(default='icon-tumble-dry', help_text='Clase CSS del ícono 5', max_length=50)),
                ('care_text_5', models.CharField(default='Tumble dry, medium hear.', max_length=200)),
                ('product_code_text', models.CharField(default='LT01: 70% wool, 15% polyester, 10% polyamide, 5% acrylic 900 Grms/mt', help_text='Texto que aparece debajo de los íconos SVG', max_length=300)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contenido Global de Productos',
                'verbose_name_plural': 'Contenido Global de Productos',
            },
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ProductCare',
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
