# Generated by Django 5.2.7 on 2025-12-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_globalproductcontent_remove_productfeature_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.variante')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'producto', 'variante')},
            },
        ),
    ]
