# Generated by Django 5.2.5 on 2026-01-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bajo_pedido',
            field=models.BooleanField(default=False, help_text='Si está activado, el producto seguirá visible aunque no tenga stock. Si está desactivado, se eliminará automáticamente al agotarse.'),
        ),
    ]
