# Generated by Django 5.2.5 on 2026-01-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_producto_bajo_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['posicion', 'created_at'], 'verbose_name': 'Imagen/Video', 'verbose_name_plural': 'Imágenes/Videos'},
        ),
        migrations.AddField(
            model_name='imagen',
            name='tipo_medio',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', help_text='Tipo de medio', max_length=10),
        ),
        migrations.AddField(
            model_name='imagen',
            name='video',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4, WebM)', null=True, upload_to='productos/videos/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagenes/'),
        ),
    ]
