# Generated by Django 5.2.5 on 2026-01-27 18:33

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_imagen_options_imagen_tipo_medio_imagen_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Archivo de imagen (JPG, PNG, GIF, WebP) - Resolución original mantenida', null=True, upload_to='productos/imagenes/', validators=[apps.productos.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='video',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4, WebM, MOV) - Resolución original mantenida', null=True, upload_to='productos/videos/', validators=[apps.productos.models.validate_video_extension]),
        ),
    ]
