# Generated by Django 5.2.5 on 2026-01-27 18:46

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_alter_imagen_imagen_alter_imagen_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Archivo de imagen (JPG, PNG, GIF, WebP, HEIC/iPhone) - Resolución original mantenida', null=True, upload_to='productos/imagenes/', validators=[apps.productos.models.validate_image_extension]),
        ),
    ]
