# Generated by Django 5.2.5 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_alter_imagen_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('pending_new_products', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de campaña de marketing',
                'verbose_name_plural': 'Estado de campañas de marketing',
            },
        ),
    ]
