# Generated by Django 5.2.5 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_marketingcampaignstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='imagen_mobile',
            field=models.ImageField(blank=True, help_text='Imagen para móviles (opcional)', null=True, upload_to='colecciones/mobile/'),
        ),
    ]
