# Generated by Django 5.2.5 on 2026-09-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_producto_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='color_texto',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco')], default='negro', help_text='Color del texto para el título en el slider', max_length=10),
        ),
    ]
