# Generated by Django 5.2.5 on 2025-11-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReturnInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Shipping & Delivery', help_text='Título que aparece en el modal', max_length=100)),
                ('delivery_titulo', models.CharField(default='Delivery', help_text='Título de la sección de envíos', max_length=50)),
                ('delivery_texto_1', models.TextField(default='All orders shipped with UPS Express.', help_text='Primera línea de información de envío')),
                ('delivery_texto_2', models.TextField(default='Always free shipping for orders over US $250.', help_text='Segunda línea de información de envío')),
                ('delivery_texto_3', models.TextField(default='All orders are shipped with a UPS tracking number.', help_text='Tercera línea de información de envío')),
                ('returns_titulo', models.CharField(default='Returns', help_text='Título de la sección de devoluciones', max_length=50)),
                ('returns_texto_1', models.TextField(default='Items returned within 14 days of their original shipment date in same as new condition will be eligible for a full refund or store credit.', help_text='Primera línea de información de devoluciones')),
                ('returns_texto_2', models.TextField(default='Refunds will be charged back to the original form of payment used for purchase.', help_text='Segunda línea de información de devoluciones')),
                ('returns_texto_3', models.TextField(default='Customer is responsible for shipping charges when making returns and shipping/handling fees of original purchase is non-refundable.', help_text='Tercera línea de información de devoluciones')),
                ('returns_texto_4', models.TextField(default='All sale items are final purchases.', help_text='Cuarta línea de información de devoluciones')),
                ('help_titulo', models.CharField(default='Help', help_text='Título de la sección de ayuda', max_length=50)),
                ('help_texto', models.TextField(default='Give us a shout if you have any other questions and/or concerns.', help_text='Texto de introducción de ayuda')),
                ('help_email', models.EmailField(default='contact@domain.com', help_text='Email de contacto', max_length=254)),
                ('help_telefono', models.CharField(default='+1 (23) 456 789', help_text='Teléfono de contacto', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Solo puede haber un registro activo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de Envío y Devoluciones',
                'verbose_name_plural': 'Información de Envío y Devoluciones',
            },
        ),
    ]
