# Generated by Django 5.2.5 on 2025-11-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=20, verbose_name='Tipo de descuento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo del carrito para aplicar el descuento', max_digits=10, verbose_name='Monto mínimo de compra')),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Número máximo de veces que puede usarse (dejar vacío para ilimitado)', null=True, verbose_name='Usos máximos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos actuales')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Código de Descuento',
                'verbose_name_plural': 'Códigos de Descuento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de descuento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de descuento'),
        ),
    ]
