# Generated by Django 5.2.5 on 2025-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_codigodescuento_pedido_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
