# Generated by Django 5.2.5 on 2025-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_fecha_pago_pedido_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título o nombre de la imagen (opcional)', max_length=100, null=True)),
                ('imagen', models.ImageField(help_text='Imagen para el slider', upload_to='about-us/')),
                ('posicion', models.PositiveIntegerField(default=0, help_text='Orden en que aparecerá en el slider (0 = primera)')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar esta imagen en el slider')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen About Us',
                'verbose_name_plural': 'Imágenes About Us',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision_titulo', models.CharField(default='Our mission', help_text='Título de la sección de misión', max_length=100)),
                ('mision_texto', models.TextField(default='Our mission is to empower people through sustainable fashion. We want everyone to look and feel good, while also doing our part to help the environment. We believe that fashion should be stylish, affordable and accessible to everyone. Body positivity and inclusivity are values that are at the heart of our brand.', help_text='Texto descriptivo de la misión')),
                ('activo', models.BooleanField(default=True, help_text='Solo puede haber un registro activo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('imagenes_slider', models.ManyToManyField(blank=True, help_text='Imágenes que aparecerán en el slider (en orden de posición)', related_name='about_us_slider', to='core.aboutusimage')),
            ],
            options={
                'verbose_name': 'Página About Us',
                'verbose_name_plural': 'Página About Us',
            },
        ),
    ]
