# Generated by Django 5.2.5 on 2025-12-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutusimage_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='imagenes_slider',
        ),
        migrations.AddField(
            model_name='aboutusimage',
            name='about_us',
            field=models.ForeignKey(default=1, help_text='Página About Us a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_slider', to='core.aboutus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mision_texto',
            field=models.TextField(default='Our mission is to empower people through sustainable fashion...', help_text='Texto descriptivo de la misión'),
        ),
    ]
