# Generated by Django 5.2.7 on 2025-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_aboutus_imagenes_slider_aboutusimage_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
    ]
