# Generated by Django 5.2.7 on 2026-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedido_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('terms-conditions', 'Términos y Condiciones'), ('privacy-policy', 'Política de Privacidad'), ('delivery-return', 'Devoluciones y Cambios'), ('shipping', 'Envíos')], max_length=50, unique=True, verbose_name='Tipo de página')),
                ('titulo', models.CharField(help_text='Título de la página', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido HTML de la página (puedes usar etiquetas HTML)')),
                ('seo_meta_description', models.CharField(blank=True, help_text='Descripción para SEO (máx 160 caracteres)', max_length=160, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Mostrar esta página')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Información',
                'verbose_name_plural': 'Páginas de Información',
                'ordering': ['slug'],
            },
        ),
    ]
