# Generated by Django 5.2.5 on 2026-02-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_infopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPage',
        ),
    ]
