# Generated by Django 5.2.5 on 2025-11-15 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si es una compra verificada'),
        ),
        migrations.CreateModel(
            name='RespuestaResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='resenas.resena')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta a Reseña',
                'verbose_name_plural': 'Respuestas a Reseñas',
                'ordering': ['creado_en'],
            },
        ),
    ]
