# Generated by Django 5.2.5 on 2025-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
