# Generated by Django 5.2.5 on 2025-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_imagen_file_alter_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='file',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='posicion',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='imagen',
            constraint=models.CheckConstraint(condition=models.Q(('producto__isnull', False), ('variante__isnull', False), _connector='OR'), name='imagen_producto_o_variante_not_null'),
        ),
    ]
