# Generated by Django 5.2.5 on 2025-11-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_imagen_options_remove_imagen_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
