"""
Django settings for selenashop project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3+#xyc#bp9k!gl@vc2_e-%fl#0i0_^$li-k%5j*xc1xqvn^uw9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Para filtros como intcomma
    # Apps propias
    'apps.usuarios',
    'apps.productos',
    'apps.resenas',
    'apps.ayudas',
    'core',
    'storages',
]
AUTH_USER_MODEL = 'usuarios.Usuario'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CartPersistenceMiddleware',  # Sincronizar carrito a BD
    'core.admin_middleware.AdminAccessMiddleware',  # Proteger rutas de administración
]

# AWS CONFIG
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'selenastore-bucket')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-2')  # Ohio

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

ROOT_URLCONF = 'selenashop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Use a string path to avoid any Path/PosixPath subtlety when Django
        # constructs filesystem paths during template lookup.
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'admin-ecomus'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.categorias_menu',
                'core.context_processors.cart',
                'core.context_processors.delivery_return_info',
                'core.context_processors.wishlist_count',
                'apps.ayudas.context_processors.datos_contacto',
            ],
        },
    },
]

WSGI_APPLICATION = 'selenashop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'selenashopdb',
        'USER': 'postgres',
        'PASSWORD': 'admin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Static URL used during development. Keep different from MEDIA_URL.
STATIC_URL = '/static/'
# In production use collectstatic to populate STATIC_ROOT and serve from a web server.
STATIC_ROOT = BASE_DIR / 'staticfiles'  # where collectstatic puts files for production
# Tell Django where to find the project-level static files directory.
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Archivos estáticos del proyecto
]

# Media (user-uploaded) files served at /media/ during development
# MEDIA FILES
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
# MEDIA_ROOT = BASE_DIR / 'media'  # Commented out since using S3

# Configuración para archivos multimedia
# No limitar el tamaño de archivos subidos (por defecto Django no tiene límite)
# Si el servidor web tiene límites, configurarlos allí
DATA_UPLOAD_MAX_MEMORY_SIZE = None  # Sin límite para archivos en memoria
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB en memoria antes de ir a disco

# Tipos de archivo permitidos para videos
ALLOWED_VIDEO_EXTENSIONS = ['.mp4', '.webm', '.mov', '.avi']
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.heic', '.heif']

# No comprimir imágenes ni videos - mantener calidad original
# Django no comprime por defecto, pero esta configuración es para referencia

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Shopping Cart Configuration
CART_SESSION_ID = 'cart'
# ==================== EMAIL CONFIGURATION ====================
# Configuración con Resend (moderno, sin problemas SSL, 3000 emails/mes gratis)

import os

# Detectar si estamos en producción
PRODUCTION = os.environ.get('PRODUCTION', 'False') == 'True'

if PRODUCTION:
    # ===== CONFIGURACIÓN PARA PRODUCCIÓN =====
    # Usar Resend con variables de entorno
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = 'resend'
    EMAIL_HOST_PASSWORD = os.environ.get('RESEND_API_KEY', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Selena Shop <noreply@selenashop.com>')
else:
    # ===== CONFIGURACIÓN PARA DESARROLLO CON RESEND =====
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.resend.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = 'resend'
    EMAIL_HOST_PASSWORD = 're_5jwJYjfR_NjHxPi4WQ9GemJqbCcWKyCoz'
    DEFAULT_FROM_EMAIL = 'Selena Shop <onboarding@resend.dev>'  # Email verificado por Resend
    EMAIL_TIMEOUT = 10

# Tiempo de expiración del token de restablecimiento (en segundos)
PASSWORD_RESET_TIMEOUT = 86400  # 24 horas

# Tiempo de expiración del token de verificación de email (en horas)
EMAIL_VERIFICATION_TIMEOUT_HOURS = 48

# ==================== CONFIGURACIÓN META WHATSAPP BUSINESS API ====================
# IMPORTANTE: Obtener estas credenciales desde Meta Business Console
# 1. Phone Number ID: https://business.facebook.com → WhatsApp Manager → Phone Numbers
# 2. Access Token: https://developers.facebook.com/apps → Settings → Tokens
# 3. Admin Phone: Número telefónico del administrador (formato internacional: +593979607739)

# Tokens y IDs de Meta WhatsApp API
WHATSAPP_PHONE_NUMBER_ID = 'YOUR_PHONE_NUMBER_ID'  # Reemplazar con tu Phone Number ID
WHATSAPP_BUSINESS_ACCOUNT_ID = 'YOUR_BUSINESS_ACCOUNT_ID'  # ID de cuenta de negocio
WHATSAPP_ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'  # Token de acceso Meta
WHATSAPP_ADMIN_NUMBER = '+593989387657'  # Número del admin (formato internacional)
WHATSAPP_API_URL = 'https://graph.instagram.com/v18.0'  # URL base de la API

# Para desarrollo, puede usar variables de entorno:
# import os
# WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
# WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
# WHATSAPP_ADMIN_NUMBER = os.getenv('WHATSAPP_ADMIN_NUMBER', '+593979607739')

