"""
Django settings for selenashop project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3+#xyc#bp9k!gl@vc2_e-%fl#0i0_^$li-k%5j*xc1xqvn^uw9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Para filtros como intcomma
    # Apps propias
    'apps.usuarios',
    'apps.productos',
    'apps.resenas',
    'core',
]
AUTH_USER_MODEL = 'usuarios.Usuario'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'selenashop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Use a string path to avoid any Path/PosixPath subtlety when Django
        # constructs filesystem paths during template lookup.
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'admin-ecomus'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.categorias_menu',
                'core.context_processors.cart',
                'core.context_processors.delivery_return_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'selenashop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Static URL used during development. Keep different from MEDIA_URL.
STATIC_URL = '/static/'
# In production use collectstatic to populate STATIC_ROOT and serve from a web server.
STATIC_ROOT = BASE_DIR / 'staticfiles'  # where collectstatic puts files for production
# Tell Django where to find the project-level static files directory.
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Archivos estáticos del proyecto
]

# Media (user-uploaded) files served at /media/ during development
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Shopping Cart Configuration
CART_SESSION_ID = 'cart'

# Email Configuration
# Usar SMTP de Gmail para envío real de correos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# IMPORTANTE: Configurar estas variables con tus credenciales de Gmail
# Para EMAIL_HOST_PASSWORD, debes generar una "Contraseña de aplicación" en:
# https://myaccount.google.com/apppasswords (requiere verificación en 2 pasos activada)
EMAIL_HOST_USER = 'marcojaramillo0142@gmail.com'  # Cambiar por tu email de Gmail
EMAIL_HOST_PASSWORD = 'vckw tnfr ekag rhsn'  # Cambiar por tu contraseña de aplicación (16 caracteres sin espacios)

DEFAULT_FROM_EMAIL = 'Selena Shop <marcojaramillo0142@gmail.com>'  # Cambiar por tu email

# Para desarrollo (solo imprime en consola, descomentar si no quieres enviar emails reales):
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Tiempo de expiración del token de restablecimiento (en segundos)
PASSWORD_RESET_TIMEOUT = 86400  # 24 horas

# Tiempo de expiración del token de verificación de email (en horas)
EMAIL_VERIFICATION_TIMEOUT_HOURS = 48

# ==================== CONFIGURACIÓN WHATSAPP BUSINESS API (META) ====================
# IMPORTANTE: Configurar estas variables con tus credenciales de Meta/WhatsApp Business
# 
# Pasos para obtener las credenciales:
# 1. Ir a https://developers.facebook.com/
# 2. Crear una app y activar WhatsApp Business API
# 3. Obtener el Access Token desde la sección de Tokens
# 4. Obtener el Phone Number ID de tu número de WhatsApp Business
# 5. Obtener el Business Account ID
#
# Variables de configuración:
WHATSAPP_ACCESS_TOKEN = ''  # Reemplazar con tu Access Token
WHATSAPP_PHONE_NUMBER_ID = ''  # Reemplazar con tu Phone Number ID
WHATSAPP_BUSINESS_ACCOUNT_ID = ''  # Reemplazar con tu Business Account ID
WHATSAPP_ADMIN_NUMBER = '593979607739'  # Número del admin (en formato internacional, sin +)

# Para desarrollo/pruebas, puedes usar variables de entorno:
# import os
# WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
# WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')
# WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv('WHATSAPP_BUSINESS_ACCOUNT_ID', '')
# WHATSAPP_ADMIN_NUMBER = os.getenv('WHATSAPP_ADMIN_NUMBER', '593979607739')
