# Generated by Django 5.2.7 on 2026-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terminos', 'Términos y Condiciones'), ('devoluciones', 'Devoluciones y Cambios'), ('envios', 'Envíos'), ('privacidad', 'Política de Privacidad')], help_text='Tipo de página de ayuda', max_length=20, unique=True)),
                ('titulo', models.CharField(help_text='Título de la página', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido HTML o texto de la página')),
                ('activo', models.BooleanField(default=True, help_text='Activar/Desactivar esta página de ayuda')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de Ayuda',
                'verbose_name_plural': 'Páginas de Ayuda',
                'ordering': ['tipo'],
            },
        ),
    ]
