# Generated by Django 5.2.7 on 2026-01-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (ej: Compras, Pagos, Envíos)', max_length=100)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve de la categoría', max_length=300)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el frontend')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar/Ocultar esta categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría FAQ',
                'verbose_name_plural': 'Categorías FAQ',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text='Texto de la pregunta', max_length=300)),
                ('respuesta', models.TextField(help_text='Respuesta a la pregunta (puede contener HTML básico)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden dentro de la categoría')),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar esta pregunta destacada')),
                ('activo', models.BooleanField(default=True, help_text='Mostrar/Ocultar esta pregunta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ayudas.categoriafaq')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['categoria', 'orden', 'pregunta'],
            },
        ),
    ]
