# Generated by Django 5.2.7 on 2026-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0002_categoriafaq_preguntafrecuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Av. Principal 123, Quito, Ecuador', help_text='Dirección de la tienda', max_length=300)),
                ('email', models.EmailField(default='info@selenashop.com', help_text='Email de contacto principal', max_length=254)),
                ('telefono', models.CharField(default='+593 99 999 9999', help_text='Número de teléfono', max_length=20)),
                ('facebook', models.URLField(blank=True, help_text='URL de Facebook (opcional)')),
                ('instagram', models.URLField(blank=True, help_text='URL de Instagram (opcional)')),
                ('tiktok', models.URLField(blank=True, help_text='URL de TikTok (opcional)')),
                ('twitter', models.URLField(blank=True, help_text='URL de Twitter/X (opcional)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de Contacto',
                'verbose_name_plural': 'Datos de Contacto',
            },
        ),
    ]
