# Generated by Django 5.2.7 on 2026-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0003_datoscontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='URL de Google Maps para la ubicación de la tienda (ej: https://maps.app.goo.gl/...)'),
        ),
    ]
