# Generated by Django 5.2.5 on 2026-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0004_datoscontacto_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='whatsapp_pedidos',
            field=models.CharField(default='0979184413', help_text='Número de WhatsApp donde llegarán los pedidos (sin código de país o con el, ej: 593979184413)', max_length=20),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='direccion',
            field=models.CharField(default='Av. 25 de Junio y Páez, Machala, El Oro', help_text='Dirección de la tienda', max_length=300),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='email',
            field=models.EmailField(default='selenastore.oficial.ec@gmail.com', help_text='Email de contacto principal', max_length=254),
        ),
        migrations.AlterField(
            model_name='datoscontacto',
            name='telefono',
            field=models.CharField(default='0979184413', help_text='Número de teléfono', max_length=20),
        ),
    ]
