# Generated by Django 5.2.5 on 2026-04-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0005_datoscontacto_whatsapp_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='mostrar_envios_devoluciones',
            field=models.BooleanField(default=True, help_text='Activar o desactivar la sección "Envío y Devolución" en los productos'),
        ),
        migrations.AddField(
            model_name='datoscontacto',
            name='mostrar_guia_tallas',
            field=models.BooleanField(default=False, help_text='Activar o desactivar el enlace "Encuentra tu talla" en los productos'),
        ),
    ]
