# Generated by Django 5.2.5 on 2026-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas', '0006_datoscontacto_mostrar_envios_devoluciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título sobre la imagen (opcional)', max_length=200)),
                ('subtitulo', models.CharField(blank=True, help_text='Texto debajo del título (opcional)', max_length=300)),
                ('imagen', models.ImageField(help_text='Imagen desktop (recomendado: 1920x720px)', upload_to='slider/')),
                ('imagen_mobile', models.ImageField(blank=True, help_text='Imagen para móvil (recomendado: 768x900px, opcional)', null=True, upload_to='slider/mobile/')),
                ('enlace_url', models.CharField(blank=True, help_text='URL destino al hacer clic (ej: /collections/ o https://...)', max_length=500)),
                ('texto_boton', models.CharField(blank=True, default='Ver más', help_text='Texto del botón (opcional)', max_length=80)),
                ('orden', models.PositiveIntegerField(default=10, help_text='Orden en el slider (menor = antes). Las colecciones aparecen primero.')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide Personalizado',
                'verbose_name_plural': 'Slides Personalizados',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
