# Generated by Django 5.2.5 on 2025-12-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
