# Generated by Django 5.2.5 on 2026-01-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-creado'], 'verbose_name': 'Código de recuperación', 'verbose_name_plural': 'Códigos de recuperación'},
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
