# Generated by Django 5.2.5 on 2026-01-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_passwordresetcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carnival_coupon_used_2026',
            field=models.BooleanField(default=False, help_text='Si el usuario ya usó el cupón del 10% de carnaval febrero 2026'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='carnival_coupon_used_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que usó el cupón de carnaval', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
