# Generated by Django 5.2.5 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_carnival_coupon_used_2026_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Indica si el usuario acepta recibir comunicaciones publicitarias.'),
        ),
    ]
