# Generated by Django 5.2.5 on 2026-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario acepta recibir comunicaciones publicitarias.'),
        ),
    ]
